service: graphqlapi

provider:
  name: aws
  runtime: nodejs12.x
  versionFunctions: true

# plugins:
#   - serverless-express

plugins:
  - express

functions:
  graphql_handler:
    handler: app.execute
    events:
      - http:
          path: /
          method: POST
          cors: true
